#!/bin/bash
# =============================================================================
# Install the scheduler driver as a systemd service, so it starts at boot and is
# restarted after a crash. The systemd counterpart of start-scheduler-tmux.sh,
# taking the same arguments.
# =============================================================================
# Why a SYSTEM unit (installed with sudo, running as you) and not a user unit:
# the AWS head node runs systemd 219 (Amazon Linux 2), where `systemctl --user`
# has no D-Bus session at all. Every setting below works on 219.
#
# Usage:
#   install-scheduler-service.sh <queue_file> [default_library] [default_wave_size]
#                                [default_queue] [--dry-run]
#   install-scheduler-service.sh --print <same args>   # render the unit, install nothing
#
# Env forwarded into the unit when set: S3_BUCKET POLL_SECONDS ON_FAIL
# AUTO_FETCH_SIF STATE_FILE. LOG_DIR is always written, resolved the same way the
# driver resolves it. PATH is captured from THIS shell: run it from a login shell
# where `squeue` works, because the unit inherits nothing else.
#
# Rerun it to change the arguments (then restart the service). Rerun it after a
# head-node replacement: the unit lives in /etc on the root disk, not on /shared.
# =============================================================================

set -uo pipefail

UNIT="${SCHEDULER_UNIT:-ersilia-scheduler}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

usage() { sed -n '12,15p' "$0" | sed 's/^# \{0,1\}//'; exit "${1:-1}"; }
die() { echo "ERROR: $*" >&2; exit 1; }

PRINT=0
ARGS=()
for a in "$@"; do
    case "$a" in
        --print)   PRINT=1 ;;
        -h|--help) usage 0 ;;
        *)         ARGS+=("$a") ;;
    esac
done
[ "${#ARGS[@]}" -ge 1 ] || usage

# systemd splits ExecStart= on whitespace and expands % and $ itself; refuse
# anything it would reinterpret rather than attempt to escape it.
safe() {  # $1 = what, $2 = value
    case "$2" in
        *[[:space:]%\$\\\"\']*) die "$1 contains a space, quote, %, \$ or backslash: $2" ;;
    esac
}

QUEUE_FILE="${ARGS[0]}"
[ -f "$QUEUE_FILE" ] || die "queue file not found: $QUEUE_FILE"
ARGS[0]="$(cd "$(dirname "$QUEUE_FILE")" && pwd)/$(basename "$QUEUE_FILE")"
for a in "${ARGS[@]}"; do safe "argument" "$a"; done
safe "script directory" "$SCRIPT_DIR"

# Resolve LOG_DIR exactly as the driver will: environment > scheduler.conf > default.
SCHEDULER_CONF="${SCHEDULER_CONF:-${SCRIPT_DIR}/scheduler.conf}"
# shellcheck source=/dev/null
[ -f "$SCHEDULER_CONF" ] && source "$SCHEDULER_CONF"
LOG_DIR="${LOG_DIR:-/shared/logs/scheduler}"
safe "LOG_DIR" "$LOG_DIR"

# A unit gets almost no PATH and never reads /etc/profile.d. Without /opt/slurm/bin
# scancel and squeue fail silently — and a failed squeue reads as "keep waiting",
# so a wave would hang forever. Capture the PATH that works here, and prove it.
for bin in sbatch squeue scancel; do
    command -v "$bin" >/dev/null 2>&1 \
        || die "'$bin' is not on PATH. Run this from a shell where SLURM commands work."
done
safe "PATH" "$PATH"

RUN_USER="$(id -un)"
RUN_GROUP="$(id -gn)"

env_lines() {
    echo "Environment=\"PATH=${PATH}\""
    echo "Environment=\"LOG_DIR=${LOG_DIR}\""
    local var
    for var in S3_BUCKET POLL_SECONDS ON_FAIL AUTO_FETCH_SIF STATE_FILE; do
        if [ -n "${!var:-}" ]; then
            safe "$var" "${!var}"
            echo "Environment=\"${var}=${!var}\""
        fi
    done
}

render() {
    cat <<EOF
# Generated by install-scheduler-service.sh — edit by rerunning it, not by hand.
[Unit]
Description=Ersilia model scheduler driver (${LOG_DIR})
Wants=network-online.target
After=network-online.target remote-fs.target slurmctld.service
RequiresMountsFor=${SCRIPT_DIR} ${LOG_DIR}

[Service]
Type=simple
User=${RUN_USER}
Group=${RUN_GROUP}
WorkingDirectory=${SCRIPT_DIR}
$(env_lines)
ExecStart=${SCRIPT_DIR}/scheduler-service.sh start ${ARGS[*]}
ExecStopPost=${SCRIPT_DIR}/scheduler-service.sh stop-post

# Stop = SIGTERM to the driver ONLY, so its trap can kill the orchestrator and
# scancel the array in the right order. The default (control-group) would signal
# the orchestrator at the same moment — setsid does not escape a cgroup — and if
# it died first, the array would never be cancelled.
KillMode=mixed
# The trap runs only after the current foreground command (e.g. an S3 recount)
# returns, then spends up to ~11s on TERM->KILL before scancel. If even this is
# exceeded, ExecStopPost still cancels the array.
TimeoutStopSec=180
# The driver exits 130/143 from its INT/TERM traps. Without this a deliberate
# "systemctl stop" would count as a failure, and Restart= would undo it.
SuccessExitStatus=130 143

Restart=on-failure
RestartSec=30
# 75 = another driver holds the lock: fail once, loudly, rather than loop.
RestartPreventExitStatus=75
# systemd 219 spells these in [Service] (newer versions moved them to [Unit]).
StartLimitInterval=600
StartLimitBurst=5

[Install]
WantedBy=multi-user.target
EOF
}

if [ "$PRINT" -eq 1 ]; then
    render
    exit 0
fi

command -v systemctl >/dev/null 2>&1 || die "systemctl not found — use start-scheduler-tmux.sh on this machine."

ACTIVE=0
systemctl is-active --quiet "$UNIT" 2>/dev/null && ACTIVE=1

# A driver started some other way (tmux, by hand) would hold the lock, and the
# service would fail its first start with exit 75. Say so up front instead.
if [ "$ACTIVE" -eq 0 ]; then
    # shellcheck source=/dev/null
    source "${SCRIPT_DIR}/scheduler-lib.sh" || die "cannot source scheduler-lib.sh"
    for pid in $(pgrep -u "$(id -u)" -f 'run-model-queue\.sh' 2>/dev/null); do
        is_driver_process "$pid" || continue
        env_dir="$(tr '\0' '\n' < "/proc/${pid}/environ" 2>/dev/null | sed -n 's/^LOG_DIR=//p' | head -n 1)"
        if [ -z "$env_dir" ] || [ "$env_dir" = "$LOG_DIR" ]; then
            die "a driver is already running for ${LOG_DIR} (pid ${pid}, probably in tmux).
       Stop it first:  ${SCRIPT_DIR}/sched-ctl.sh --log-dir ${LOG_DIR} shutdown"
        fi
    done
fi

TARGET="/etc/systemd/system/${UNIT}.service"
tmp="$(mktemp)" || die "cannot create a temporary file"
trap 'rm -f "$tmp"' EXIT
render > "$tmp"

sudo install -m 0644 "$tmp" "$TARGET" || die "could not write $TARGET (sudo)"
sudo systemctl daemon-reload || die "systemctl daemon-reload failed"
sudo systemctl enable "$UNIT" || die "systemctl enable failed"

if [ "$ACTIVE" -eq 1 ]; then
    echo "Updated ${TARGET}. The running driver keeps its old settings until:"
    echo "  sudo systemctl restart ${UNIT}"
else
    sudo systemctl start "$UNIT" || die "systemctl start failed — see: sudo journalctl -u ${UNIT}"
    echo "Installed and started ${UNIT} (${TARGET})."
fi
echo "  status     : sudo systemctl status ${UNIT}"
echo "  stop       : sudo systemctl stop ${UNIT}      (stays stopped until started)"
echo "  unit events: sudo journalctl -u ${UNIT}"
echo "  driver log : ${LOG_DIR}/driver.log"
